name: ะก++ division by zero validation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Pull the Docker image
        run: |
          mkdir out
          docker pull yegor256/c2eo:0.1.24
      - name: Run the Docker image
        run: docker run -v $(pwd):/eo yegor256/c2eo:0.1.24 examples/hello.c out/global.eo
      - name: Check out/global.eo
        run: cat out/global.eo
      - name: Run Polystat Jar
        run: bash polystat.sh
      - name: Check polystat-eo-out.txt
        run: cat polystat-eo-out.txt
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: polystat-eo-out
          path: polystat-eo-out.txt
